// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace IceCompactId
{
}

namespace Demo
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface CallbackReceiver : Ice.Object, CallbackReceiverOperations_, CallbackReceiverOperationsNC_
    {
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface CallbackSender : Ice.Object, CallbackSenderOperations_, CallbackSenderOperationsNC_
    {
    }
}

namespace Demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public delegate void Callback_CallbackReceiver_callback();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public delegate void Callback_CallbackSender_initiateCallback();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public delegate void Callback_CallbackSender_shutdown();
}

namespace Demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface CallbackReceiverPrx : Ice.ObjectPrx
    {
        void callback();

        void callback(_System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult<Demo.Callback_CallbackReceiver_callback> begin_callback();

        Ice.AsyncResult<Demo.Callback_CallbackReceiver_callback> begin_callback(_System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_callback(Ice.AsyncCallback cb__, object cookie__);

        Ice.AsyncResult begin_callback(_System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_callback(Ice.AsyncResult r__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface CallbackSenderPrx : Ice.ObjectPrx
    {
        void initiateCallback(Demo.CallbackReceiverPrx proxy);

        void initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult<Demo.Callback_CallbackSender_initiateCallback> begin_initiateCallback(Demo.CallbackReceiverPrx proxy);

        Ice.AsyncResult<Demo.Callback_CallbackSender_initiateCallback> begin_initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_initiateCallback(Demo.CallbackReceiverPrx proxy, Ice.AsyncCallback cb__, object cookie__);

        Ice.AsyncResult begin_initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_initiateCallback(Ice.AsyncResult r__);

        void shutdown();

        void shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult<Demo.Callback_CallbackSender_shutdown> begin_shutdown();

        Ice.AsyncResult<Demo.Callback_CallbackSender_shutdown> begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_shutdown(Ice.AsyncCallback cb__, object cookie__);

        Ice.AsyncResult begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_shutdown(Ice.AsyncResult r__);
    }
}

namespace Demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface CallbackReceiverOperations_
    {
        void callback(Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface CallbackReceiverOperationsNC_
    {
        void callback();
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface CallbackSenderOperations_
    {
        void initiateCallback(Demo.CallbackReceiverPrx proxy, Ice.Current current__);

        void shutdown(Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface CallbackSenderOperationsNC_
    {
        void initiateCallback(Demo.CallbackReceiverPrx proxy);

        void shutdown();
    }
}

namespace Demo
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public sealed class CallbackReceiverPrxHelper : Ice.ObjectPrxHelperBase, CallbackReceiverPrx
    {
        #region Synchronous operations

        public void callback()
        {
            this.callback(null, false);
        }

        public void callback(_System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            this.callback(ctx__, true);
        }

        private void callback(_System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_callback(begin_callback(context__, explicitCtx__, true, null, null));
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<Demo.Callback_CallbackReceiver_callback> begin_callback()
        {
            return begin_callback(null, false, false, null, null);
        }

        public Ice.AsyncResult<Demo.Callback_CallbackReceiver_callback> begin_callback(_System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_callback(ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_callback(Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_callback(null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_callback(_System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_callback(ctx__, true, false, cb__, cookie__);
        }

        private const string __callback_name = "callback";

        public void end_callback(Ice.AsyncResult r__)
        {
            end__(r__, __callback_name);
        }

        private Ice.AsyncResult<Demo.Callback_CallbackReceiver_callback> begin_callback(_System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<Demo.Callback_CallbackReceiver_callback> result__ = getOnewayOutgoingAsync<Demo.Callback_CallbackReceiver_callback>(__callback_name, callback_completed__, cookie__);
            if (cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__callback_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                result__.writeEmptyParams();
                result__.invoke();
            }
            catch (Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void callback_completed__(Demo.Callback_CallbackReceiver_callback cb__)
        {
            if (cb__ != null)
            {
                cb__();
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx b)
        {
            if (b == null)
            {
                return null;
            }
            CallbackReceiverPrx r = b as CallbackReceiverPrx;
            if ((r == null) && b.ice_isA(ice_staticId()))
            {
                CallbackReceiverPrxHelper h = new CallbackReceiverPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if (b == null)
            {
                return null;
            }
            CallbackReceiverPrx r = b as CallbackReceiverPrx;
            if ((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                CallbackReceiverPrxHelper h = new CallbackReceiverPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if (b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if (bb.ice_isA(ice_staticId()))
                {
                    CallbackReceiverPrxHelper h = new CallbackReceiverPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch (Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if (b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if (bb.ice_isA(ice_staticId(), ctx))
                {
                    CallbackReceiverPrxHelper h = new CallbackReceiverPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch (Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static CallbackReceiverPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if (b == null)
            {
                return null;
            }
            CallbackReceiverPrx r = b as CallbackReceiverPrx;
            if (r == null)
            {
                CallbackReceiverPrxHelper h = new CallbackReceiverPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static CallbackReceiverPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if (b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            CallbackReceiverPrxHelper h = new CallbackReceiverPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::Demo::CallbackReceiver",
            "::Ice::Object"
        };

        public static string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Marshaling support

        public static void write__(IceInternal.BasicStream os__, CallbackReceiverPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static CallbackReceiverPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if (proxy != null)
            {
                CallbackReceiverPrxHelper result = new CallbackReceiverPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public sealed class CallbackSenderPrxHelper : Ice.ObjectPrxHelperBase, CallbackSenderPrx
    {
        #region Synchronous operations

        public void initiateCallback(Demo.CallbackReceiverPrx proxy)
        {
            this.initiateCallback(proxy, null, false);
        }

        public void initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            this.initiateCallback(proxy, ctx__, true);
        }

        private void initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_initiateCallback(begin_initiateCallback(proxy, context__, explicitCtx__, true, null, null));
        }

        public void shutdown()
        {
            this.shutdown(null, false);
        }

        public void shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            this.shutdown(ctx__, true);
        }

        private void shutdown(_System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_shutdown(begin_shutdown(context__, explicitCtx__, true, null, null));
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<Demo.Callback_CallbackSender_initiateCallback> begin_initiateCallback(Demo.CallbackReceiverPrx proxy)
        {
            return begin_initiateCallback(proxy, null, false, false, null, null);
        }

        public Ice.AsyncResult<Demo.Callback_CallbackSender_initiateCallback> begin_initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_initiateCallback(proxy, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_initiateCallback(Demo.CallbackReceiverPrx proxy, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_initiateCallback(proxy, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_initiateCallback(proxy, ctx__, true, false, cb__, cookie__);
        }

        private const string __initiateCallback_name = "initiateCallback";

        public void end_initiateCallback(Ice.AsyncResult r__)
        {
            end__(r__, __initiateCallback_name);
        }

        private Ice.AsyncResult<Demo.Callback_CallbackSender_initiateCallback> begin_initiateCallback(Demo.CallbackReceiverPrx proxy, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<Demo.Callback_CallbackSender_initiateCallback> result__ = getOnewayOutgoingAsync<Demo.Callback_CallbackSender_initiateCallback>(__initiateCallback_name, initiateCallback_completed__, cookie__);
            if (cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__initiateCallback_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                Demo.CallbackReceiverPrxHelper.write__(os__, proxy);
                result__.endWriteParams();
                result__.invoke();
            }
            catch (Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void initiateCallback_completed__(Demo.Callback_CallbackSender_initiateCallback cb__)
        {
            if (cb__ != null)
            {
                cb__();
            }
        }

        public Ice.AsyncResult<Demo.Callback_CallbackSender_shutdown> begin_shutdown()
        {
            return begin_shutdown(null, false, false, null, null);
        }

        public Ice.AsyncResult<Demo.Callback_CallbackSender_shutdown> begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_shutdown(ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_shutdown(Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_shutdown(null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_shutdown(ctx__, true, false, cb__, cookie__);
        }

        private const string __shutdown_name = "shutdown";

        public void end_shutdown(Ice.AsyncResult r__)
        {
            end__(r__, __shutdown_name);
        }

        private Ice.AsyncResult<Demo.Callback_CallbackSender_shutdown> begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<Demo.Callback_CallbackSender_shutdown> result__ = getOnewayOutgoingAsync<Demo.Callback_CallbackSender_shutdown>(__shutdown_name, shutdown_completed__, cookie__);
            if (cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__shutdown_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                result__.writeEmptyParams();
                result__.invoke();
            }
            catch (Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void shutdown_completed__(Demo.Callback_CallbackSender_shutdown cb__)
        {
            if (cb__ != null)
            {
                cb__();
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static CallbackSenderPrx checkedCast(Ice.ObjectPrx b)
        {
            if (b == null)
            {
                return null;
            }
            CallbackSenderPrx r = b as CallbackSenderPrx;
            if ((r == null) && b.ice_isA(ice_staticId()))
            {
                CallbackSenderPrxHelper h = new CallbackSenderPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static CallbackSenderPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if (b == null)
            {
                return null;
            }
            CallbackSenderPrx r = b as CallbackSenderPrx;
            if ((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                CallbackSenderPrxHelper h = new CallbackSenderPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static CallbackSenderPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if (b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if (bb.ice_isA(ice_staticId()))
                {
                    CallbackSenderPrxHelper h = new CallbackSenderPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch (Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static CallbackSenderPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if (b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if (bb.ice_isA(ice_staticId(), ctx))
                {
                    CallbackSenderPrxHelper h = new CallbackSenderPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch (Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static CallbackSenderPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if (b == null)
            {
                return null;
            }
            CallbackSenderPrx r = b as CallbackSenderPrx;
            if (r == null)
            {
                CallbackSenderPrxHelper h = new CallbackSenderPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static CallbackSenderPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if (b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            CallbackSenderPrxHelper h = new CallbackSenderPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::Demo::CallbackSender",
            "::Ice::Object"
        };

        public static string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Marshaling support

        public static void write__(IceInternal.BasicStream os__, CallbackSenderPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static CallbackSenderPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if (proxy != null)
            {
                CallbackSenderPrxHelper result = new CallbackSenderPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }
}

namespace Demo
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public abstract class CallbackReceiverDisp_ : Ice.ObjectImpl, CallbackReceiver
    {
        #region Slice operations

        public void callback()
        {
            callback(Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void callback(Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ =
        {
            "::Demo::CallbackReceiver",
            "::Ice::Object"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[0];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[0];
        }

        public static new string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus callback___(CallbackReceiver obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            inS__.readEmptyParams();
            obj__.callback(current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "callback",
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if (pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch (pos)
            {
                case 0:
                    {
                        return callback___(this, inS__, current__);
                    }
                case 1:
                    {
                        return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                    }
                case 2:
                    {
                        return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                    }
                case 3:
                    {
                        return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                    }
                case 4:
                    {
                        return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                    }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        protected override void writeImpl__(IceInternal.BasicStream os__)
        {
            os__.startWriteSlice(ice_staticId(), -1, true);
            os__.endWriteSlice();
        }

        protected override void readImpl__(IceInternal.BasicStream is__)
        {
            is__.startReadSlice();
            is__.endReadSlice();
        }

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public abstract class CallbackSenderDisp_ : Ice.ObjectImpl, CallbackSender
    {
        #region Slice operations

        public void initiateCallback(Demo.CallbackReceiverPrx proxy)
        {
            initiateCallback(proxy, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void initiateCallback(Demo.CallbackReceiverPrx proxy, Ice.Current current__);

        public void shutdown()
        {
            shutdown(Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void shutdown(Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ =
        {
            "::Demo::CallbackSender",
            "::Ice::Object"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[0];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[0];
        }

        public static new string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus initiateCallback___(CallbackSender obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            Demo.CallbackReceiverPrx proxy;
            proxy = Demo.CallbackReceiverPrxHelper.read__(is__);
            inS__.endReadParams();
            obj__.initiateCallback(proxy, current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus shutdown___(CallbackSender obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            inS__.readEmptyParams();
            obj__.shutdown(current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping",
            "initiateCallback",
            "shutdown"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if (pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch (pos)
            {
                case 0:
                    {
                        return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                    }
                case 1:
                    {
                        return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                    }
                case 2:
                    {
                        return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                    }
                case 3:
                    {
                        return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                    }
                case 4:
                    {
                        return initiateCallback___(this, inS__, current__);
                    }
                case 5:
                    {
                        return shutdown___(this, inS__, current__);
                    }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        protected override void writeImpl__(IceInternal.BasicStream os__)
        {
            os__.startWriteSlice(ice_staticId(), -1, true);
            os__.endWriteSlice();
        }

        protected override void readImpl__(IceInternal.BasicStream is__)
        {
            is__.startReadSlice();
            is__.endReadSlice();
        }

        #endregion
    }
}
