// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace IceCompactId
{
}

namespace demo
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface ICallback : Ice.Object, ICallbackOperations_, ICallbackOperationsNC_
    {
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface Printer : Ice.Object, PrinterOperations_, PrinterOperationsNC_
    {
    }
}

namespace demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public delegate void Callback_ICallback_doback();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public delegate void Callback_Printer_InitCallback();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public delegate void Callback_Printer_printString();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public delegate void Callback_Printer_sendImage();
}

namespace demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface ICallbackPrx : Ice.ObjectPrx
    {
        void doback(string date);

        void doback(string date, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult<demo.Callback_ICallback_doback> begin_doback(string date);

        Ice.AsyncResult<demo.Callback_ICallback_doback> begin_doback(string date, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_doback(string date, Ice.AsyncCallback cb__, object cookie__);

        Ice.AsyncResult begin_doback(string date, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_doback(Ice.AsyncResult r__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface PrinterPrx : Ice.ObjectPrx
    {
        void InitCallback(demo.ICallbackPrx callback);

        void InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult<demo.Callback_Printer_InitCallback> begin_InitCallback(demo.ICallbackPrx callback);

        Ice.AsyncResult<demo.Callback_Printer_InitCallback> begin_InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_InitCallback(demo.ICallbackPrx callback, Ice.AsyncCallback cb__, object cookie__);

        Ice.AsyncResult begin_InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_InitCallback(Ice.AsyncResult r__);

        void printString(string s);

        void printString(string s, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult<demo.Callback_Printer_printString> begin_printString(string s);

        Ice.AsyncResult<demo.Callback_Printer_printString> begin_printString(string s, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_printString(string s, Ice.AsyncCallback cb__, object cookie__);

        Ice.AsyncResult begin_printString(string s, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_printString(Ice.AsyncResult r__);

        void sendImage(byte[] seq, string name);

        void sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult<demo.Callback_Printer_sendImage> begin_sendImage(byte[] seq, string name);

        Ice.AsyncResult<demo.Callback_Printer_sendImage> begin_sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_sendImage(byte[] seq, string name, Ice.AsyncCallback cb__, object cookie__);

        Ice.AsyncResult begin_sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_sendImage(Ice.AsyncResult r__);
    }
}

namespace demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface ICallbackOperations_
    {
        void doback(string date, Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface ICallbackOperationsNC_
    {
        void doback(string date);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface PrinterOperations_
    {
        void InitCallback(demo.ICallbackPrx callback, Ice.Current current__);

        void printString(string s, Ice.Current current__);

        void sendImage(byte[] seq, string name, Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public interface PrinterOperationsNC_
    {
        void InitCallback(demo.ICallbackPrx callback);

        void printString(string s);

        void sendImage(byte[] seq, string name);
    }
}

namespace demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public sealed class ByteSeqHelper
    {
        public static void write(IceInternal.BasicStream os__, byte[] v__)
        {
            os__.writeByteSeq(v__);
        }

        public static byte[] read(IceInternal.BasicStream is__)
        {
            byte[] v__;
            v__ = is__.readByteSeq();
            return v__;
        }
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public sealed class ICallbackPrxHelper : Ice.ObjectPrxHelperBase, ICallbackPrx
    {
        #region Synchronous operations

        public void doback(string date)
        {
            this.doback(date, null, false);
        }

        public void doback(string date, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            this.doback(date, ctx__, true);
        }

        private void doback(string date, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_doback(begin_doback(date, context__, explicitCtx__, true, null, null));
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<demo.Callback_ICallback_doback> begin_doback(string date)
        {
            return begin_doback(date, null, false, false, null, null);
        }

        public Ice.AsyncResult<demo.Callback_ICallback_doback> begin_doback(string date, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_doback(date, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_doback(string date, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_doback(date, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_doback(string date, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_doback(date, ctx__, true, false, cb__, cookie__);
        }

        private const string __doback_name = "doback";

        public void end_doback(Ice.AsyncResult r__)
        {
            end__(r__, __doback_name);
        }

        private Ice.AsyncResult<demo.Callback_ICallback_doback> begin_doback(string date, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<demo.Callback_ICallback_doback> result__ = getOnewayOutgoingAsync<demo.Callback_ICallback_doback>(__doback_name, doback_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__doback_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                os__.writeString(date);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void doback_completed__(demo.Callback_ICallback_doback cb__)
        {
            if(cb__ != null)
            {
                cb__();
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static ICallbackPrx checkedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            ICallbackPrx r = b as ICallbackPrx;
            if((r == null) && b.ice_isA(ice_staticId()))
            {
                ICallbackPrxHelper h = new ICallbackPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static ICallbackPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            ICallbackPrx r = b as ICallbackPrx;
            if((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                ICallbackPrxHelper h = new ICallbackPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static ICallbackPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId()))
                {
                    ICallbackPrxHelper h = new ICallbackPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static ICallbackPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId(), ctx))
                {
                    ICallbackPrxHelper h = new ICallbackPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static ICallbackPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            ICallbackPrx r = b as ICallbackPrx;
            if(r == null)
            {
                ICallbackPrxHelper h = new ICallbackPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static ICallbackPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            ICallbackPrxHelper h = new ICallbackPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::Ice::Object",
            "::demo::ICallback"
        };

        public static string ice_staticId()
        {
            return ids__[1];
        }

        #endregion

        #region Marshaling support

        public static void write__(IceInternal.BasicStream os__, ICallbackPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static ICallbackPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if(proxy != null)
            {
                ICallbackPrxHelper result = new ICallbackPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public sealed class PrinterPrxHelper : Ice.ObjectPrxHelperBase, PrinterPrx
    {
        #region Synchronous operations

        public void InitCallback(demo.ICallbackPrx callback)
        {
            this.InitCallback(callback, null, false);
        }

        public void InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            this.InitCallback(callback, ctx__, true);
        }

        private void InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_InitCallback(begin_InitCallback(callback, context__, explicitCtx__, true, null, null));
        }

        public void printString(string s)
        {
            this.printString(s, null, false);
        }

        public void printString(string s, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            this.printString(s, ctx__, true);
        }

        private void printString(string s, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_printString(begin_printString(s, context__, explicitCtx__, true, null, null));
        }

        public void sendImage(byte[] seq, string name)
        {
            this.sendImage(seq, name, null, false);
        }

        public void sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            this.sendImage(seq, name, ctx__, true);
        }

        private void sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_sendImage(begin_sendImage(seq, name, context__, explicitCtx__, true, null, null));
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<demo.Callback_Printer_InitCallback> begin_InitCallback(demo.ICallbackPrx callback)
        {
            return begin_InitCallback(callback, null, false, false, null, null);
        }

        public Ice.AsyncResult<demo.Callback_Printer_InitCallback> begin_InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_InitCallback(callback, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_InitCallback(demo.ICallbackPrx callback, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_InitCallback(callback, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_InitCallback(callback, ctx__, true, false, cb__, cookie__);
        }

        private const string __InitCallback_name = "InitCallback";

        public void end_InitCallback(Ice.AsyncResult r__)
        {
            end__(r__, __InitCallback_name);
        }

        private Ice.AsyncResult<demo.Callback_Printer_InitCallback> begin_InitCallback(demo.ICallbackPrx callback, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<demo.Callback_Printer_InitCallback> result__ = getOnewayOutgoingAsync<demo.Callback_Printer_InitCallback>(__InitCallback_name, InitCallback_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__InitCallback_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                demo.ICallbackPrxHelper.write__(os__, callback);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void InitCallback_completed__(demo.Callback_Printer_InitCallback cb__)
        {
            if(cb__ != null)
            {
                cb__();
            }
        }

        public Ice.AsyncResult<demo.Callback_Printer_printString> begin_printString(string s)
        {
            return begin_printString(s, null, false, false, null, null);
        }

        public Ice.AsyncResult<demo.Callback_Printer_printString> begin_printString(string s, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_printString(s, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_printString(string s, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_printString(s, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_printString(string s, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_printString(s, ctx__, true, false, cb__, cookie__);
        }

        private const string __printString_name = "printString";

        public void end_printString(Ice.AsyncResult r__)
        {
            end__(r__, __printString_name);
        }

        private Ice.AsyncResult<demo.Callback_Printer_printString> begin_printString(string s, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<demo.Callback_Printer_printString> result__ = getOnewayOutgoingAsync<demo.Callback_Printer_printString>(__printString_name, printString_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__printString_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                os__.writeString(s);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void printString_completed__(demo.Callback_Printer_printString cb__)
        {
            if(cb__ != null)
            {
                cb__();
            }
        }

        public Ice.AsyncResult<demo.Callback_Printer_sendImage> begin_sendImage(byte[] seq, string name)
        {
            return begin_sendImage(seq, name, null, false, false, null, null);
        }

        public Ice.AsyncResult<demo.Callback_Printer_sendImage> begin_sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_sendImage(seq, name, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_sendImage(byte[] seq, string name, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_sendImage(seq, name, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_sendImage(seq, name, ctx__, true, false, cb__, cookie__);
        }

        private const string __sendImage_name = "sendImage";

        public void end_sendImage(Ice.AsyncResult r__)
        {
            end__(r__, __sendImage_name);
        }

        private Ice.AsyncResult<demo.Callback_Printer_sendImage> begin_sendImage(byte[] seq, string name, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<demo.Callback_Printer_sendImage> result__ = getOnewayOutgoingAsync<demo.Callback_Printer_sendImage>(__sendImage_name, sendImage_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__sendImage_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                demo.ByteSeqHelper.write(os__, seq);
                os__.writeString(name);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void sendImage_completed__(demo.Callback_Printer_sendImage cb__)
        {
            if(cb__ != null)
            {
                cb__();
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static PrinterPrx checkedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            PrinterPrx r = b as PrinterPrx;
            if((r == null) && b.ice_isA(ice_staticId()))
            {
                PrinterPrxHelper h = new PrinterPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static PrinterPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            PrinterPrx r = b as PrinterPrx;
            if((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                PrinterPrxHelper h = new PrinterPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static PrinterPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId()))
                {
                    PrinterPrxHelper h = new PrinterPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static PrinterPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId(), ctx))
                {
                    PrinterPrxHelper h = new PrinterPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static PrinterPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            PrinterPrx r = b as PrinterPrx;
            if(r == null)
            {
                PrinterPrxHelper h = new PrinterPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static PrinterPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            PrinterPrxHelper h = new PrinterPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::Ice::Object",
            "::demo::Printer"
        };

        public static string ice_staticId()
        {
            return ids__[1];
        }

        #endregion

        #region Marshaling support

        public static void write__(IceInternal.BasicStream os__, PrinterPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static PrinterPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if(proxy != null)
            {
                PrinterPrxHelper result = new PrinterPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }
}

namespace demo
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public abstract class ICallbackDisp_ : Ice.ObjectImpl, ICallback
    {
        #region Slice operations

        public void doback(string date)
        {
            doback(date, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void doback(string date, Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ = 
        {
            "::Ice::Object",
            "::demo::ICallback"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[1];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[1];
        }

        public static new string ice_staticId()
        {
            return ids__[1];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus doback___(ICallback obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            string date;
            date = is__.readString();
            inS__.endReadParams();
            obj__.doback(date, current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "doback",
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if(pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch(pos)
            {
                case 0:
                {
                    return doback___(this, inS__, current__);
                }
                case 1:
                {
                    return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                }
                case 2:
                {
                    return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                }
                case 3:
                {
                    return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                }
                case 4:
                {
                    return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        protected override void writeImpl__(IceInternal.BasicStream os__)
        {
            os__.startWriteSlice(ice_staticId(), -1, true);
            os__.endWriteSlice();
        }

        protected override void readImpl__(IceInternal.BasicStream is__)
        {
            is__.startReadSlice();
            is__.endReadSlice();
        }

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.3")]
    public abstract class PrinterDisp_ : Ice.ObjectImpl, Printer
    {
        #region Slice operations

        public void InitCallback(demo.ICallbackPrx callback)
        {
            InitCallback(callback, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void InitCallback(demo.ICallbackPrx callback, Ice.Current current__);

        public void printString(string s)
        {
            printString(s, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void printString(string s, Ice.Current current__);

        public void sendImage(byte[] seq, string name)
        {
            sendImage(seq, name, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void sendImage(byte[] seq, string name, Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ = 
        {
            "::Ice::Object",
            "::demo::Printer"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[1];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[1];
        }

        public static new string ice_staticId()
        {
            return ids__[1];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus InitCallback___(Printer obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            demo.ICallbackPrx callback;
            callback = demo.ICallbackPrxHelper.read__(is__);
            inS__.endReadParams();
            obj__.InitCallback(callback, current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus printString___(Printer obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            string s;
            s = is__.readString();
            inS__.endReadParams();
            obj__.printString(s, current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus sendImage___(Printer obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            byte[] seq;
            string name;
            seq = demo.ByteSeqHelper.read(is__);
            name = is__.readString();
            inS__.endReadParams();
            obj__.sendImage(seq, name, current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "InitCallback",
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping",
            "printString",
            "sendImage"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if(pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch(pos)
            {
                case 0:
                {
                    return InitCallback___(this, inS__, current__);
                }
                case 1:
                {
                    return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                }
                case 2:
                {
                    return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                }
                case 3:
                {
                    return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                }
                case 4:
                {
                    return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                }
                case 5:
                {
                    return printString___(this, inS__, current__);
                }
                case 6:
                {
                    return sendImage___(this, inS__, current__);
                }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        protected override void writeImpl__(IceInternal.BasicStream os__)
        {
            os__.startWriteSlice(ice_staticId(), -1, true);
            os__.endWriteSlice();
        }

        protected override void readImpl__(IceInternal.BasicStream is__)
        {
            is__.startReadSlice();
            is__.endReadSlice();
        }

        #endregion
    }
}
