//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPort.Server.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class personrepositoryEntities : DbContext
    {
        public personrepositoryEntities()
            : base("name=personrepositoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<person> persons { get; set; }
        public virtual DbSet<persontag> persontags { get; set; }
        public virtual DbSet<persontagview> persontagviews { get; set; }
    }
}
