//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPort.Server.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public string FaceID { get; set; }
        public string UUID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string ImageData1 { get; set; }
        public string SignatureCode1 { get; set; }
        public string ImageData2 { get; set; }
        public string SignatureCode2 { get; set; }
        public string ImageData3 { get; set; }
        public string SignatureCode3 { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
